### ISSUE TITLE
v7 BOM info request

### ISSUE THREAD

**Issue by mrgw454** [epearsoe/MIB238#1]
Hi Eric.  I'm interested in building this project and looking over the BOM along with your comments in the README.md file about changes for v7 of your board.  The only component I can't find information on looks to be a voltage regulator (5v to 3.3v).  I'm guessing that's for the WiFi module?  Would you happen to have any information about that item?  Thank you!

**Comment by JohnLundy** [comment]
STMicroelectronics P/N# L4931CZ33-AP - LDO Voltage Regulators 3.3V 0.25A Positive

Yes, it is for powering the WiFi module.

**Comment by mrgw454** [comment]
> STMicroelectronics P/N# L4931CZ33-AP - LDO Voltage Regulators 3.3V 0.25A Positive
> 
> Yes, it is for powering the WiFi module.

Hi John -- thank you very much for that information.  I really appreciate it!

**Comment by mrgw454** [comment]
John was nice enough to provide the information.  Closing issue.
